[package]
name = "lassie"
version = "0.0.1"
authors = ["Al McElrath <hello@yrns.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
peg = "0.7.0"
rustc-ap-rustc_lexer = "719.0.0"
